<a href="https://colab.research.google.com/github/sadidoll/Artifical-Interlligence/blob/master/HW1_Prob2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Problem 2**:

 Inside a colab notebook implement a Python function multiply_matrices that takes as input a list of numpy arrays and outputs their product. It should raise a custom exception if there is a pair of incompatible matrices. The exception message should provide information about which pair of matrices is bad. Make sure that you follow the style guide for Python. Also use simple markup for formatting your notebook and include a simple description of what your program does inside a text cell. You should also use some simple Latex commands, for instance, when explaining what it means for two matrices to be compatible.





#### **A function to multiply matrices**

In [0]:
import numpy as np
def multiply_matrices(input):
  # n is a variable that iterates over each matrix
  n = 1
  l = len(input)
  if l <= 1:
    raise Exception("Empty list!! Please enter atleast 2 matrices to multiply")
    return
  A = input[0]
  try:
    for i in range(l -  1):
      B = input[n]
      result = np.matmul(A,B)
      # increment n so that it can multiply with the other matrix
      n = n + 1 
      A = result
    print(result)
  except ValueError as err:
    raise Exception("The following matrices are not compatible :\n The column of the matrix shown below: \n"
     + np.array2string(A) + "\n is not equal to the row of matrix shown below:\n" + np.array2string(B))


In order to do matrices multiplication, the column of the first matrix has to be equal to the second matrix. The following matrices shown are compatible for multiplication: 

$$\begin{bmatrix}
    a  &  b      \\
    c  &  d
\end{bmatrix} _{2 \times 2}
\times
\begin{bmatrix}
    e  &  f  &  g      \\
    h  &  i  &  j
\end{bmatrix}_{2 \times 3}
=
\begin{bmatrix}
    (a \times e) + (b \times h)  &  (a \times f) + (b \times i)  &  (a \times g) + (b \times j)      \\
    (c \times e) + (d \times h)  &  (c \times f) + (d \times i)  &  (c \times g) + (d \times j)      \\
\end{bmatrix}_{2 \times 3}$$

#### Below is a test case to show the multiplication of matrices by calling the function multiply_matrices().

In [43]:
A = np.array([[1, 5, 3], [6, 7, 8], [2, 4, 9]])
B = np.array([[3, 0], [10, -4], [2, 7]])
C = np.array([[6, 1, 2], [2, -3, 3]])
result = [A,B,C]
multiply_matrices(result)

[[356  56 121]
 [680  20 292]
 [478 -77 269]]


#### Below is a test case to demonstrate that it raises an exception if the matrix are not compatible for multiplication:

In [44]:
A = np.array([[1, 5, 3], [6, 7, 8], [2, 4, 9]])
B = np.array([[3, 0], [10, -4], [2, 7]])
C = np.array([[6, 1, 8], [4, 7, 0],[2, -1, 3]])
result = [A,B,C]
multiply_matrices(result)

Exception: ignored

#### Below is a test case to demonstarte that it raises exception if the list is empty:

In [45]:
result = []
multiply_matrices(result)

Exception: ignored