<a href="https://colab.research.google.com/github/sadidoll/Artifical-Interlligence/blob/master/HW_4/Homework4_p1_%26_p_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Homework 4**

###**Problem 1**
Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.

Note that the size s of the kernel matrix can also be an even number

**Imports**

In [0]:
import numpy as np

**Function for conv2d using numpy**

In [0]:
def conv2d(input_mat, kernal_mat):
  # Checking if the input given by the user are square matrix
  if (input_mat.shape[0] != input_mat.shape[1]):
    raise ValueError("Error: The Input Matrix is not a square matrix")
  if (kernal_mat.shape[0] != kernal_mat.shape[1]):
    raise ValueError("Error: The Kernal Matrix is not a square matrix")
  # Checks if the kernal is larger than input
  if (kernal_mat.shape[0] > input_mat.shape[0]):
    raise ValueError("Error: The kernal can't be larger than input ")
  
  # Creating output array
  output_mat = np.zeros((input_mat.shape[0] - kernal_mat.shape[0] + 1 ,
                        input_mat.shape[1] - kernal_mat.shape[1] + 1))
 
  # Source: https://stackoverflow.com/questions/2448015/2d-convolution-using-python-and-numpy
  # Convolving
  for i in range(input_mat.shape[0] - kernal_mat.shape[0] + 1):
    for j in range(input_mat.shape[1] - kernal_mat.shape[1] + 1):
      output_mat[i][j] = np.sum(input_mat[i: i + kernal_mat.shape[0],
                                          j : j + kernal_mat.shape[1]] * kernal_mat)
  return output_mat


**Testing the conv2d function with some test cases**

In [11]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])


for i in range(len(input_mat)):
  try:
    # uncomment line for student code testing
    output_mat = conv2d(input_mat[i], kernel_mat[i])
    print(output_mat)
   
    # uncomment lines below (and comment line above) for generating test cases.
    if np.array_equal(output_mat, expected_mat[i]):
      print("Correct output!\n")
    else:
      print("Incorrect output!\n")
  except Exception as e:
    print(e)

    if expected_mat[i] == []:
      print("Correct output!\n")
    else:
      print("Incorrect output!\n")


[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!

Error: The kernal can't be larger than input 
Correct output!



###**Problem 2**

Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.


**Function for 2d max pooling using numpy**

In [0]:
def maxpooling2d(input_mat, s):

  # Checks if the input is square matrix
  if(input_mat.shape[0] != input_mat.shape[1]):
    raise ValueError("Error: The Input Matrix is not a square matrix ")
  
  # Checks if the window size is larger than input 
  if(s > input_mat.shape[0]):
    raise ValueError("Error: The size of the window cannot be larger than the input")
  
  # Creating empty matrix to hold the result
  output_mat = np.empty((int(input_mat.shape[0] / s),
                         int(input_mat.shape[1] / s)))
  # Maxpooling
  for i in range(int(input_mat.shape[0] / s)):
    n = i * s
    for j in range(int(input_mat.shape[1] / s)):
      m = j * s
      # Finding the max
      output_mat[i][j] = np.amax(input_mat[n: n + s, m : m + s])
  
  return output_mat


**Testing the 2d max pooling function**

In [29]:
#import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                              [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                           [2, 4, 2, 1, 0, 3],
                           [1, 2, 4, 2, 4, 5],
                           [2, 1, 2, 1, 2, 1],
                           [1, 1, 2, 3, 1, 2],
                           [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
                    [2, 4, 5],
                    [1, 3, 2]])


for i in range(len(input_mat)):
  try:
    # uncomment top line and comment second line to test code
    output_mat = maxpooling2d(input_mat[i], s[i])
    #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)
    print(output_mat)
    if np.array_equal(output_mat, expected_mat[i]):
      print("Correct output!")
    else:
      print("Incorrect output!")
  except Exception as e :
    print(e)
    if expected_mat[i] == []:
      print("Correct output!")
    else:
      print("Incorrect output!")



[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
