<a href="https://colab.research.google.com/github/sadidoll/Artifical-Interlligence/blob/master/Hw_4/Homework4_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Homework 4**

###**Problem 1**
Using only numpy, implement the function conv2d. It takes as input input_mat and kernel_mat and outputs output_mat. All variables are square matrices. It should compute the convolution of input_mat with the kernel kernel_mat using valid padding.

Note that the size s of the kernel matrix can also be an even number

**Imports**

In [0]:
import numpy as np

**Function for conv2d using numpy**

In [0]:
def conv2d(input_mat, kernal_mat):
  # Checking if the input given by the user are square matrix
  if (input_mat.shape[0] != input_mat.shape[1]):
    raise ValueError("Error: The Input Matrix is not a square matrix")
  if (kernal_mat.shape[0] != kernal_mat.shape[1]):
    raise ValueError("Error: The Kernal Matrix is not a square matrix")
  # Checks if the kernal is larger than input
  if (kernal_mat.shape[0] > input_mat.shape[0]):
    raise ValueError("Error: The kernal can't be larger than input ")
  
  # Creating output array
  output_mat = np.zeros((input_mat.shape[0] - kernal_mat.shape[0] + 1 ,
                        input_mat.shape[0] - kernal_mat.shape[0] + 1))
  
  # Convolving
  for i in range(input_mat.shape[0] - kernal_mat.shape[0] + 1):
    for j in range(input_mat.shape[0] - kernal_mat.shape[0] + 1):
      output_mat[i][j] = np.sum(input_mat[i: i + kernal_mat.shape[0],
                                          j : j + kernal_mat.shape[0]] * kernal_mat)
  return output_mat


**Testing the conv2d function with some test cases**

In [24]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])


for i in range(len(input_mat)):
  try:
    # uncomment line for student code testing
    output_mat = conv2d(input_mat[i], kernel_mat[i])
    print(output_mat)
   
    # uncomment lines below (and comment line above) for generating test cases.
    if np.array_equal(output_mat, expected_mat[i]):
      print("Correct output!\n")
    else:
      print("Incorrect output!\n")
  except Exception as e:
    print(e)

    if expected_mat[i] == []:
      print("Correct output!\n")
    else:
      print("Incorrect output!\n")


[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!

Error: The kernal can't be larger than input 
Correct output!

